/**
 * Stripe webhook fan-out. Handles two distinct billing flows:
 *
 *   - **Charity subscriptions** (existing): `checkout.session.completed`
 *     with `metadata.charity_id` → recurring partner subscription. Updated
 *     state lives on `charities.stripe_subscription_id` + status.
 *
 *   - **Landlord setup + invoices** (new): Checkout sessions with
 *     `metadata.landlord_id` (or `client_reference_id` like
 *     `landlord:<id>`) save a card via SetupIntent. Subsequent monthly
 *     invoices generated by the cron emit `invoice.paid` /
 *     `invoice.payment_failed` events that update the local mirror in
 *     `landlord_invoices`.
 *
 * Idempotency: every event handler is written to be safe under retries —
 * Stripe replays a webhook a few times if our 2xx is delayed. We rely on
 * UNIQUE(stripe_invoice_id) in the DB and `IS NULL` guards on the setup
 * stamp so duplicate deliveries leave state unchanged.
 *
 * Routing: we check `metadata.landlord_id` BEFORE `metadata.charity_id` so
 * a session can only belong to one role's flow. Sessions with neither are
 * ignored (not an error — could be a future flow we haven't wired yet).
 */

import { NextResponse } from "next/server";
import type Stripe from "stripe";
import { sql } from "@/lib/db/index";
import { getStripe } from "@/lib/stripe";
import {
  getLandlordById,
  getPropertyById,
  setLandlordBilling,
  updateInvoiceFromStripe,
} from "@/lib/db/landlords";
import {
  sendInvoicePaid,
  sendInvoicePaymentFailed,
} from "@/lib/email/landlord";

export async function POST(req: Request) {
  const stripe = getStripe();
  const body = await req.text();
  const sig = req.headers.get("stripe-signature");
  if (!sig) {
    return NextResponse.json({ error: "Missing signature" }, { status: 400 });
  }

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(
      body,
      sig,
      process.env.STRIPE_WEBHOOK_SECRET!
    );
  } catch (err) {
    console.error("[stripe.webhook] invalid signature:", err);
    return NextResponse.json({ error: "Invalid signature" }, { status: 400 });
  }

  try {
    switch (event.type) {
      case "checkout.session.completed":
        await handleCheckoutCompleted(event.data.object as Stripe.Checkout.Session, stripe);
        break;
      case "setup_intent.succeeded":
        await handleSetupIntentSucceeded(event.data.object as Stripe.SetupIntent);
        break;
      case "customer.subscription.updated":
      case "customer.subscription.deleted":
        await handleCharitySubscriptionEvent(event.data.object as Stripe.Subscription);
        break;
      case "invoice.finalized":
      case "invoice.paid":
      case "invoice.payment_failed":
      case "invoice.voided":
      case "invoice.marked_uncollectible":
        await handleInvoiceEvent(event.type, event.data.object as Stripe.Invoice);
        break;
      default:
        // Unhandled event types are fine — Stripe sends a lot we don't care
        // about. Returning 200 prevents Stripe from retrying.
        break;
    }
  } catch (err) {
    console.error(`[stripe.webhook] handler for ${event.type} threw:`, err);
    // 500 makes Stripe retry the webhook with backoff. For idempotent
    // handlers (which all of ours are) this is the right behavior.
    return NextResponse.json({ error: "Handler failed" }, { status: 500 });
  }

  return NextResponse.json({ received: true });
}

/* -------------------------------------------------------------------------- */
/* Checkout completion — disambiguate landlord setup vs. charity subscription */
/* -------------------------------------------------------------------------- */

async function handleCheckoutCompleted(s: Stripe.Checkout.Session, stripe: Stripe) {
  // Prefer metadata.landlord_id; fall back to client_reference_id pattern.
  const landlordId =
    s.metadata?.landlord_id ??
    (s.client_reference_id?.startsWith("landlord:")
      ? s.client_reference_id.slice("landlord:".length)
      : null);

  if (landlordId && s.mode === "setup") {
    // SetupIntent ran inside this Checkout session — pull the saved
    // payment method off it and persist as the landlord's default card.
    let paymentMethodId: string | null = null;
    if (typeof s.setup_intent === "string") {
      const intent = await stripe.setupIntents.retrieve(s.setup_intent);
      paymentMethodId =
        typeof intent.payment_method === "string"
          ? intent.payment_method
          : intent.payment_method?.id ?? null;
    } else if (s.setup_intent && typeof s.setup_intent !== "string") {
      const intent = s.setup_intent as Stripe.SetupIntent;
      paymentMethodId =
        typeof intent.payment_method === "string"
          ? intent.payment_method
          : intent.payment_method?.id ?? null;
    }
    await setLandlordBilling(landlordId, {
      stripe_customer_id: typeof s.customer === "string" ? s.customer : undefined,
      default_payment_method_id: paymentMethodId ?? undefined,
      mark_setup_complete: true,
    });
    return;
  }

  // Existing charity flow — recurring subscription completed.
  const charityId = s.metadata?.charity_id;
  const subscriptionId = typeof s.subscription === "string" ? s.subscription : null;
  if (charityId && subscriptionId) {
    await sql`
      UPDATE charities SET
        stripe_subscription_id = ${subscriptionId},
        subscription_status = 'active',
        is_partner = true,
        updated_at = NOW()
      WHERE id = ${charityId}
    `;
  }
}

/* -------------------------------------------------------------------------- */
/* SetupIntent succeeded (also fires; we handle both for redundancy)          */
/* -------------------------------------------------------------------------- */

async function handleSetupIntentSucceeded(intent: Stripe.SetupIntent) {
  const landlordId = intent.metadata?.landlord_id;
  if (!landlordId) return;

  const paymentMethodId =
    typeof intent.payment_method === "string"
      ? intent.payment_method
      : intent.payment_method?.id ?? null;

  await setLandlordBilling(landlordId, {
    stripe_customer_id: typeof intent.customer === "string" ? intent.customer : undefined,
    default_payment_method_id: paymentMethodId ?? undefined,
    mark_setup_complete: true,
  });
}

/* -------------------------------------------------------------------------- */
/* Charity recurring sub state — unchanged                                    */
/* -------------------------------------------------------------------------- */

async function handleCharitySubscriptionEvent(sub: Stripe.Subscription) {
  await sql`
    UPDATE charities SET
      subscription_status = ${sub.status},
      is_partner = ${sub.status === "active"},
      updated_at = NOW()
    WHERE stripe_subscription_id = ${sub.id}
  `;
}

/* -------------------------------------------------------------------------- */
/* Landlord invoice lifecycle                                                  */
/* -------------------------------------------------------------------------- */

async function handleInvoiceEvent(eventType: string, inv: Stripe.Invoice) {
  // Only process invoices that came from our landlord-billing flow. Charity
  // subscription invoices flow through Stripe but we don't mirror them.
  const landlordId = inv.metadata?.landlord_id;
  if (!landlordId) return;
  if (!inv.id) return;

  // Map Stripe invoice events → local landlord_invoices state.
  // We rely on UNIQUE(stripe_invoice_id) so updateInvoiceFromStripe is
  // idempotent. If the row doesn't exist yet (cron crashed before insert),
  // this is a no-op — the manual generate-invoice button will reconcile.
  let status: "paid" | "open" | "void" | "uncollectible" | "failed" | undefined;
  let paidAt: string | null | undefined;
  let finalizedAt: string | null | undefined;

  switch (eventType) {
    case "invoice.finalized":
      status = "open";
      finalizedAt = new Date().toISOString();
      break;
    case "invoice.paid":
      status = "paid";
      paidAt = new Date().toISOString();
      break;
    case "invoice.payment_failed":
      status = "failed";
      break;
    case "invoice.voided":
      status = "void";
      break;
    case "invoice.marked_uncollectible":
      status = "uncollectible";
      break;
  }

  const updated = await updateInvoiceFromStripe(inv.id, {
    status,
    amount_cents: typeof inv.amount_due === "number" ? inv.amount_due : undefined,
    hosted_invoice_url: inv.hosted_invoice_url ?? null,
    paid_at: paidAt,
    finalized_at: finalizedAt,
  });

  // Notify the landlord on payment success/failure. We rely on the local
  // invoice row to find the landlord + property — the row may not exist
  // yet if `invoice.finalized` arrives before our cron writes it (rare
  // but possible). In that case, skip the email; the next event in the
  // sequence will catch it.
  if (!updated) return;
  if (eventType === "invoice.paid" || eventType === "invoice.payment_failed") {
    const [landlord, property] = await Promise.all([
      getLandlordById(updated.landlord_id),
      getPropertyById(updated.property_id),
    ]);
    if (landlord && property) {
      if (eventType === "invoice.paid") {
        void sendInvoicePaid(landlord, property, updated);
      } else {
        void sendInvoicePaymentFailed(landlord, property, updated);
      }
    }
  }
}
